import NavBar from '@/components/layouts/NavBar/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/layouts/Footer/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0',
}

export default function RootLayout({children,}: { children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className='flex flex-col h-screen'>
        <header className='bg-primary-100 px-4 fixed left-0 top-0 right-0 z-20'>
          <div className='lg:max-w-7xl py-3 md:py-6 mx-auto'>
            <NavBar/>
          </div>
        </header>
        <main className='mb-auto px-4 mt-[100px] md:mt-[164px]'>
          <div className='lg:max-w-7xl mx-auto py-4 md:py-6 md:pb-10'>
            {children}
          </div>
        </main>
        <footer className='bg-black-100 px-4'>
          <div className='lg:max-w-7xl py-6 text-white-100 mx-auto'>
            <Footer/>
          </div>
        </footer>
      </body>
    </html>
  )
}
